version: '3.1'

services:

    db:
        image: mariadb:10.7
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - 3310:3306

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            UPLOAD_LIMIT: 64M


    smtp4dev-poec:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            # Change the number before : to the port the web interface should be accessible on
            - 9082:80
            # Change the number before : to the port the SMTP server should be accessible on
            - 9026:25